/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bct_thermalcamera_ThermalCameraMLX90640 */

#ifndef _Included_bct_thermalcamera_ThermalCameraMLX90640
#define _Included_bct_thermalcamera_ThermalCameraMLX90640
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bct_thermalcamera_ThermalCameraMLX90640
 * Method:    InitialiseMLX90640
 * Signature: (Ljava/io/FileDescriptor;BI)Z
 */
JNIEXPORT jboolean JNICALL Java_bct_thermalcamera_ThermalCameraMLX90640_InitialiseMLX90640
  (JNIEnv *, jobject, jobject, jbyte, jint);

/*
 * Class:     bct_thermalcamera_ThermalCameraMLX90640
 * Method:    GetMLX90640Frame
 * Signature: (Ljava/io/FileDescriptor;B[FI)Z
 */
JNIEXPORT jboolean JNICALL Java_bct_thermalcamera_ThermalCameraMLX90640_GetMLX90640Frame
  (JNIEnv *, jobject, jobject, jbyte, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
